apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 748735308412.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest
        env:
          - name: DATABASE_HOSTNAME 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_HOSTNAME
          - name: DATABASE_PORT 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_PORT 
          - name: DATABASE_NAME 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_NAME 
          - name: ALGORITHM 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: ALGORITHM 
          - name: ACCESS_TOKEN_EXPIRE_MINUTES 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: ACCESS_TOKEN_EXPIRE_MINUTES
          - name: DATABASE_USERNAME 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_USERNAME 
          - name: DATABASE_PASSWORD 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: DATABASE_PASSWORD 
          - name: SECRET_KEY 
            valueFrom: 
              configMapKeyRef:
                name: fastapi-config
                key: SECRET_KEY  
        ports:
        - containerPort: 8000