apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DATABASE_USERNAME: cG9zdGdyZXMK
  DATABASE_PASSWORD: cGFzc3dvcmQxMjMK
  SECRET_KEY: MTRjYmZiNWQ4ZDVhNWMxYWMxNjZhZjUzNzY2NzJhZGFlODE2OGUxMDBiOGEzZjJmOWZlOGM3MDIzYTY1ZTIxOAo=